### ISSUE TITLE
Consolidate "please log in action"

### ISSUE THREAD

**Issue by DoodlingDev** [minaslater/Puppygotchi#26]
https://github.com/minaslater/Puppygotchi/blob/28a3f53da70dacd73e47f130c49bd6bd788376dd/app/controllers/puppies_controller.rb#L25

It occurs to me that there are several actions here, (actually across multiple controllers) that need to verify that the user is logged in before proceeding.

Let's consolidate that check into one method, and call it in the controllers where it's necessary.

**Comment by minaslater** [comment]
committed in add-and-delete-friends branch
